---
name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: Features
    labels:
      - feature
      - enhancement
  - title: Bug Fixes
    labels:
      - fix
      - bugfix
      - bug
  - title: Docs
    labels:
      - documentation
  - title: Internal
    labels:
      - chore
      - internal
      - refactor
      - dependencies
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: \<*_&
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: feature
    branch:
      - /^feat(ure)?[/-].+/
  - label: bug
    branch:
      - /^fix[/-].+/
      - /^bug[/-].+/
      - /^bugfix[/-].+/
  - label: chore
    branch:
      - /^chore[/-].+/
      - /^internal[/-].+/
      - /pre-commit-ci-update-config/
  - label: refactor
    branch:
      - /ref(actor)?[/-].+/
  - label: documentation
    branch:
      - /doc(umentation)?[/-].+/
  - label: enhancement
    branch:
      - /enh(ancement)?[/-].+/
